//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNumber { get; set; }
        public int Price { get; set; }
        public int Age { get; set; }
        public string Breed { get; set; }
        public string Gender { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string Currency { get; set; }
        public int UserID { get; set; }
    
        public virtual user user { get; set; }
    }
}
